from typing import Any


DESCENDING: int


class MongoCollection:
    def create_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_one(self, *args: Any, **kwargs: Any) -> Any: ...
    def find(self, *args: Any, **kwargs: Any) -> Any: ...
    def aggregate(self, *args: Any, **kwargs: Any) -> Any: ...
    def update_many(self, *args: Any, **kwargs: Any) -> Any: ...
    def update_one(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_many(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_one(self, *args: Any, **kwargs: Any) -> Any: ...
    def replace_one(self, *args: Any, **kwargs: Any) -> Any: ...


class MongoDatabase:
    def __getitem__(self, name: str) -> MongoCollection: ...


class MongoClient:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, name: str) -> MongoDatabase: ...
