from typing import Any


class Query:
    def __init__(self, default: Any = ..., **kwargs) -> None: ...


class NinjaAPI:
    def __init__(self, *args, **kwargs) -> None: ...
    def add_router(self, path: str, router: Any) -> None: ...
    def get(self, *args, **kwargs): ...
    def post(self, *args, **kwargs): ...
    def put(self, *args, **kwargs): ...
    def patch(self, *args, **kwargs): ...
    def delete(self, *args, **kwargs): ...
